"use client";

import { useState, useRef } from "react";
import Navbar from "../../components/landing/hero";
import SiteFooter from "../../components/layout/site-footer";
import ResumeBuilderInput from "../../components/builder/ResumeBuilderInput";
import GeneratedResumeCard, { type BuilderResult } from "../../components/builder/GeneratedResumeCard";
import { RunActionButton } from "../../components/watermelon-ui/run-action-button";
import {
  Zap,
  ArrowRight,
  Link2,
  Briefcase,
  Palette,
  CheckCircle,
  Target,
  Shield,
  BarChart3,
  Layers,
  Globe,
  Brain,
} from "lucide-react";
import {
  FaInbox,
  FaMagnifyingGlass,
  FaWandMagicSparkles,
  FaAward,
} from "react-icons/fa6";
import { BsFileTextFill } from "react-icons/bs";
import { TbClockHour12Filled } from "react-icons/tb";

const BUILDER_STEPS = [
  {
    num: "01",
    icon: Palette,
    title: "Select Template",
    desc: "Choose from 6 professionally designed resume templates — from Harvard Minimal for maximum ATS pass rate to Creative Sidebar for design roles.",
    color: "violet",
  },
  {
    num: "02",
    icon: Link2,
    title: "Add Portfolio Link",
    desc: "Paste your GitHub, LinkedIn, or personal portfolio URL. Our AI deep-scans all your repos, READMEs, languages, stars & descriptions automatically.",
    color: "indigo",
  },
  {
    num: "03",
    icon: Briefcase,
    title: "Add Job Description (Optional)",
    desc: "Paste the job description for highly targeted matching, or skip it to generate an overall placement-ready resume from your portfolio.",
    color: "emerald",
  },
];

const WHY_TRUST = [
  {
    icon: Target,
    title: "85+ ATS Score Average",
    desc: "Our resumes consistently score 85+ on ATS checkers thanks to keyword optimization, proper formatting, and structured content.",
  },
  {
    icon: Shield,
    title: "100% Real Data",
    desc: "We extract actual projects, skills, and technologies from your portfolio. No fabricated experience — ever.",
  },
  {
    icon: BarChart3,
    title: "Keyword-Matched",
    desc: "AI compares your portfolio against the job description and highlights matching skills, filling in gaps intelligently.",
  },
  {
    icon: Brain,
    title: "Multi-Agent Review",
    desc: "Your resume is generated by one AI agent and reviewed by another for clarity, impact, and completeness.",
  },
  {
    icon: Layers,
    title: "6 Pro Templates",
    desc: "From Harvard Minimal to Executive Premium — each template is designed for different industries and ATS systems.",
  },
  {
    icon: Globe,
    title: "Deep Portfolio Scan",
    desc: "For GitHub links, we scan all repositories, parse README files, extract languages, stars, and project descriptions.",
  },
];

export default function BuilderPage() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<BuilderResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const resultRef = useRef<HTMLDivElement>(null);

  async function handleBuild(portfolioUrl: string, jobDescription: string, templateId: string) {
    setError(null);
    setResult(null);
    setLoading(true);
    try {
      const res = await fetch("/api/build-resume", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ portfolioUrl, jobDescription, templateId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Build failed.");
      setResult(data as BuilderResult);
      setTimeout(() => {
        resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 100);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen flex flex-col bg-[#f8fafc]">
      <Navbar />

      {/* ── Hero ── */}
      <section className="relative overflow-hidden bg-white border-b border-slate-100">
        <div
          className="absolute inset-0 opacity-[0.02]"
          style={{
            backgroundImage:
              "linear-gradient(#8b5cf6 1px,transparent 1px),linear-gradient(90deg,#8b5cf6 1px,transparent 1px)",
            backgroundSize: "40px 40px",
          }}
        />
        <div className="absolute -top-24 -right-24 w-96 h-96 bg-violet-100 rounded-full blur-3xl opacity-40" />
        <div className="absolute -bottom-12 -left-12 w-64 h-64 bg-indigo-100 rounded-full blur-3xl opacity-40" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-violet-50 rounded-full blur-3xl opacity-30" />

        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 py-20 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-violet-50 border border-violet-100 text-violet-600 text-xs font-semibold mb-6 animate-fade-in">
            <Zap size={12} />
            1-Click AI Resume Builder
          </div>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-slate-900 tracking-tight leading-tight mb-5 animate-fade-in delay-100">
            Build Your Resume{" "}
            <span className="gradient-text">in One Click</span>
          </h1>
          <p className="text-lg text-slate-500 max-w-2xl mx-auto mb-8 leading-relaxed animate-fade-in delay-200">
            Paste your portfolio link with or without a job description. Our AI reads your real projects,
            matches keywords when JD is provided, and generates an ATS-optimized resume in seconds.
          </p>
          <div className="flex items-center justify-center gap-4 flex-wrap animate-fade-in delay-300">
            <a
              href="#build"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-violet-600 hover:bg-violet-700 text-white font-semibold text-sm shadow-lg shadow-violet-200 hover:shadow-xl transition-all active:scale-[0.98]"
            >
              <Zap size={15} />
              Start Building
              <ArrowRight size={14} />
            </a>
            <a
              href="#how-it-works"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl border border-slate-200 bg-white text-slate-700 font-semibold text-sm hover:border-violet-200 hover:text-violet-600 transition-all"
            >
              See How It Works
            </a>
          </div>
        </div>
      </section>

      {/* ── Steps Overview ── */}
      <section id="how-it-works" className="max-w-6xl mx-auto px-4 sm:px-6 py-20">
        <div className="text-center mb-12">
          <p className="text-xs font-semibold uppercase tracking-widest text-violet-500 mb-2">
            3 Simple Steps
          </p>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900">
            How The Builder Works
          </h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {BUILDER_STEPS.map((step, i) => {
            const Icon = step.icon;
            const colors: Record<string, { bg: string; icon: string; border: string; badge: string }> = {
              violet: { bg: "bg-violet-50", icon: "text-violet-500", border: "border-violet-100", badge: "bg-violet-600" },
              indigo: { bg: "bg-indigo-50", icon: "text-indigo-500", border: "border-indigo-100", badge: "bg-indigo-600" },
              emerald: { bg: "bg-emerald-50", icon: "text-emerald-500", border: "border-emerald-100", badge: "bg-emerald-600" },
            };
            const c = colors[step.color];
            return (
              <div
                key={step.num}
                className={`relative rounded-2xl border ${c.border} ${c.bg} p-8 hover:shadow-lg transition-all animate-slide-up`}
                style={{ animationDelay: `${i * 0.15}s` }}
              >
                {/* Step number badge */}
                <div className={`absolute -top-3 -left-1 ${c.badge} text-white text-xs font-bold px-3 py-1 rounded-full shadow-md`}>
                  Step {step.num}
                </div>
                <div className="flex items-center gap-3 mb-4 mt-2">
                  <div className={`w-11 h-11 rounded-xl bg-white flex items-center justify-center shadow-sm border ${c.border}`}>
                    <Icon size={20} className={c.icon} />
                  </div>
                  <h3 className="text-lg font-bold text-slate-900">{step.title}</h3>
                </div>
                <p className="text-sm text-slate-600 leading-relaxed">
                  {step.desc}
                </p>
              </div>
            );
          })}
        </div>

        {/* Connection line on desktop */}
        <div className="hidden md:flex items-center justify-center gap-2 mt-8">
          {[1, 2, 3].map((n) => (
            <div key={n} className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-full bg-violet-600 text-white flex items-center justify-center text-xs font-bold shadow-md">
                {n}
              </div>
              {n < 3 && (
                <div className="w-24 h-0.5 bg-gradient-to-r from-violet-300 to-indigo-300 rounded-full" />
              )}
            </div>
          ))}
        </div>
      </section>

      {/* ── Builder Form ── */}
      <section id="build" className="bg-white border-y border-slate-100">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-20">
          <div className="bg-gradient-to-br from-slate-50 to-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="px-8 py-6 border-b border-slate-100 bg-gradient-to-r from-violet-50/60 to-indigo-50/30">
              <p className="text-xs font-semibold uppercase tracking-widest text-violet-500 mb-1">
                AI Resume Builder
              </p>
              <h2 className="text-xl font-bold text-slate-900">Build from Your Portfolio</h2>
              <p className="text-sm text-slate-500 mt-1">
                We read your portfolio + the job description to craft a resume that beats ATS filters.
              </p>
            </div>
            <div className="p-8">
              <ResumeBuilderInput onSubmit={handleBuild} loading={loading} />
            </div>

            {loading && (
              <div className="px-8 pb-8 flex flex-col items-center gap-3">
                <p className="text-xs text-slate-400 font-medium uppercase tracking-widest">
                  Building Your Resume…
                </p>
                <RunActionButton
                  steps={[
                    { id: 1, label: "Reading Portfolio", icon: FaInbox },
                    { id: 2, label: "Analyzing Job", icon: FaMagnifyingGlass },
                    { id: 3, label: "Matching Keywords", icon: BsFileTextFill },
                    { id: 4, label: "Writing Resume", icon: FaWandMagicSparkles },
                    { id: 5, label: "Scoring ATS", icon: TbClockHour12Filled },
                    { id: 6, label: "Finalizing", icon: FaAward },
                  ]}
                />
              </div>
            )}

            {error && (
              <div className="mx-8 mb-8 px-4 py-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">
                ⚠️ {error}
              </div>
            )}
          </div>

          {result && (
            <div ref={resultRef} className="mt-10">
              <div className="flex items-center gap-3 mb-6">
                <div className="h-px flex-1 bg-slate-200" />
                <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 px-2">
                  Your Generated Resume
                </p>
                <div className="h-px flex-1 bg-slate-200" />
              </div>
              <GeneratedResumeCard result={result} />
            </div>
          )}
        </div>
      </section>

      {/* ── Why Trust HireLens ── */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 py-20">
        <div className="text-center mb-12">
          <p className="text-xs font-semibold uppercase tracking-widest text-violet-500 mb-2">
            Quality You Can Trust
          </p>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 mb-3">
            Why HireLens Resumes Stand Out
          </h2>
          <p className="text-slate-500 text-sm max-w-xl mx-auto">
            We don&apos;t just generate text — we build accurate, professionally structured resumes
            from your real achievements that consistently beat ATS filters.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {WHY_TRUST.map((item, i) => {
            const Icon = item.icon;
            return (
              <div
                key={item.title}
                className="rounded-2xl border border-slate-100 bg-white p-6 hover:shadow-md hover:border-violet-100 transition-all animate-slide-up"
                style={{ animationDelay: `${i * 0.08}s` }}
              >
                <div className="w-10 h-10 rounded-xl bg-violet-50 flex items-center justify-center mb-4 border border-violet-100">
                  <Icon size={18} className="text-violet-500" />
                </div>
                <h3 className="font-semibold text-slate-900 mb-1.5">{item.title}</h3>
                <p className="text-sm text-slate-500 leading-relaxed">{item.desc}</p>
              </div>
            );
          })}
        </div>

        {/* Trust bar */}
        <div className="mt-10 flex flex-wrap items-center justify-center gap-8 text-sm text-slate-400">
          {[
            { icon: CheckCircle, label: "No fabricated content" },
            { icon: Target, label: "Keyword-matched to JD" },
            { icon: Shield, label: "ATS-tested formats" },
          ].map(({ icon: Icon, label }) => (
            <div key={label} className="flex items-center gap-2">
              <Icon size={15} className="text-emerald-500" />
              <span>{label}</span>
            </div>
          ))}
        </div>
      </section>

      <SiteFooter />
    </div>
  );
}
